name: Sync Fork with Upstream

on:
  schedule:
    # 每天凌晨 1 点运行
    - cron: '0 0 * * *'
  workflow_dispatch:
    # 手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout local repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up Git
      run: |
        git config --global user.name 'woshishiq1'
        git config --global user.email '1987669587@qq.com'

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/gaotianliuyun/gao.git
        git fetch upstream

    - name: Merge upstream changes and handle conflicts
      run: |
        git merge upstream/master || true
        git merge --strategy-option=theirs || true
        git commit -am "Merged upstream changes, kept local modifications" || true

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin master || true
