name: Sync with Upstream

on:
  schedule:
    - cron: "0 0 * * *"  # Executes daily at midnight
  workflow_dispatch:    # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.name 'woshishiq1'
        git config --global user.email '1987669587@qq.com'

    - name: Add Upstream Remote
      run: git remote add upstream https://github.com/gaotianliuyun/gao.git

    - name: Fetch Upstream Changes
      run: git fetch upstream

    - name: Merge Upstream Changes
      run: |
        git checkout master  # Assuming your local branch is master
        git merge upstream/master -X theirs --allow-unrelated-histories
        # Automatically resolve conflicts by favoring the upstream changes
        git checkout --theirs .
        git add .

    - name: Push to Remote
      run: git push origin master

